name: Build & Release

on: push
jobs:
  release-site-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build the Docker image
        working-directory: ./site_generator
        run: |
          docker build . -t site_generator
          docker tag site_generator ${{ secrets.DOCKER_USERNAME }}/site_generator:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/site_generator

  release-github-wiki-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build the Docker image
        working-directory: ./github_wiki_bot
        run: |
          docker build . -t github-wiki-bot
          docker tag github-wiki-bot ${{ secrets.DOCKER_USERNAME }}/github-wiki-bot:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/github-wiki-bot